remote_theme: tuur29/pages-themes-cayman
theme: jekyll-theme-cayman
lang: es-ES
title: Ares Systems
description: La mamá de la mamá de la mamá
#logo: /docs/assets/logo.png
#logo_url: https://i.imgur.com/IOHl7OT.png
show_downloads: true
darkmode: false
hide_first_title: true
#colors:
#    gradient_left: "#F73718"
#    gradient_right: "#A42821"
#    header: "#fff"
#    android_theme: "#000"
#    link: "#1e6bb8"
#    section_title: "#f73718"
buttons:
    zip_url: http://example.com/
    zip_title: Zeus OS
             Descargar
    zip_hide: false
    tar_url: https://mega.nz/file/a8tnHa4R#iey_o1IVT33erK14hx_KcObNt7ftabp5I7RadXrXlUc
    tar_title: Ares OS
             Descargar
    tar_hide: false
    github_hide: true
